name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install node packages
        run: npm ci
      - name: Run tests
        run: xvfb-run -a npm test
      - name: Install vsce
        run: npm install -g vsce
      - name: Build vsix extension package
        run: vsce package
